[theme]
base = "light"
primaryColor = "#0D6EFD"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#212529"
font = "sans serif"

[server]
port = 8501
address = "127.0.0.1"
headless = true
gatherUsageStats = false
